name: create S3 bucket
on:
    push:
        branches: 
            - main
    workflow_dispatch:
jobs:
    terraform:
        name: 'terraform apply'
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup terraform
              uses: hashicorp/setup-terraform@v3
            - name: aws credentails
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
                  aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                  aws-region: "us-east-1"
            - name: terraform init
              run: terraform init
            - name: terraform format
              run: terraform fmt
            - name: terraform validate
              run: terraform validate
            - name: terraform plan
              run: terraform plan
            - name: terraform apply
              run: terraform apply
